# -*- coding: utf-8 -*-
"""Rule based bot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cv9jt85stzXpqUBvMICJt2hOrenwDcYq
"""

import re #String handling library
import random

import keyword
class RuleBot:
  ### potential negetive responses
  negetive_responses = ("no","nope","nah","not a chance","sorry")
  ### Exit conversation keywords
  exit_commands = ("quit","pause","exit","goodbye","bye","later")
  ### Random starter question
  random_questions = (
       "Why are you here?",
       "Are there many Nigumans like you?",
       "What do you consume for sustenance?",
       "Is there intelligent life on this planet?",
       "Does NBS have a leader?",
       "What planets have you visited?",
       "What technology do you have on this planet?"
   )

  def __init__(self):
    self.alienbabble = {'describe_planet_intent': r'.*\s*your planet.*',
                        'answer_why_intent': r'.*\s*why',
                        'about_planetsports': r'.*\s*sports'
                        }

  def greet(self):
    self.name = input("What is your name?\n")
    will_help = input(
        f"Hi {self.name}, I am Rule-Bot. Will you help me learn about your planet?\n")
    if will_help in self.negetive_responses:
      print("Ok, have a nice Earth day!")
      return
    self.chat()
  
  def make_exit(self, reply):
    for command in self.exit_commands:
      if reply == command:
        print("Okay, have a nice Earth day!")
        return True

  def make_exit2(self, reply):
    for commandd in self.negetive_responses:
      if reply == commandd:
        print("Okay, have a nice Earth day!")
        return True

  def chat(self):
    reply = input(random.choice(self.random_questions)).lower()
    while not self.make_exit(reply) or self.make_exit2(reply):
      reply = input(self.match_reply(reply))

  def match_reply(self, reply):
    for key, value in self.alienbabble.items():
      intent = key
      regex_pattern = value
      found_match = re.match(regex_pattern, reply)
      if found_match and intent == 'describe_planet_intent':
        return self.describe_planet_intent()
      elif found_match and intent == 'answer_why_intent':
        return self.answer_why_intent()
      elif found_match and intent == 'about_planetsports':
        return self.about_planetsports()
    if not found_match:
      return self.no_match_intent()


  def describe_planet_intent(self):
     responses = ("My planet is a utopia of diverse Nigumans and Nigspecies.\n",
                  "I am from Nigeshwar, the capital of the coffeway galaxy.\n "
                  "Planet I am from is in the middle of somewhere.\n",
                  "The planet of Chuckles is a bizarre place. Its inhabitants, known as Chuckloids, have elongated noses. They speak in honks and snorts, and their national anthem is a symphony of snickers and giggles.\n",
                  "Introducing Zany Zephyr, the planet where absurdity reigns supreme. The Zany Zephyrians are a quirky species with heads in the shape of jellybeans and arms that stretch to incredible lengths.\n")
     return random.choice(responses)

  def about_planetsports(self):
    responses = ("Cloud Jumping, where participants launch themselves from giant trampolines and try to land on clouds floating in the sky.\n",
                 "Zero Gravity Zogball - players must navigate a game of soccer in zero gravity, where the ball can float in any direction and players must use their entire bodies to keep it in play.\n",
                 "Cosmic Quidditch - a game of airborne wizardry where players ride broomsticks, attempt to score goals with a flying golden snitch, and dodge flying bludgers.\n",
                 "Jetpack Joust - players armed with jetpacks attempt to knock each other off balance using inflatable lances.\n",
                 "Gravity Golf - golfers play on a course with holes located on different planets, each with its own unique gravitational pull.\n")
    return random.choice(responses)

  def answer_why_intent(self):
    responses = ("I come in peace\n","I am here to collect data on best coffee on planets\n",
                 "I heard coffe is good in this Coffeway Galaxy\n","I came here to gag more about Nigumans.\n",
                 "If you provoke me we won't back down from war")
    return random.choice(responses)
  
  def no_match_intent(self):
    responses = ("Please tell me more\n", "Tell me more\n", "Why do you say so?\n","Kuch Interesting bata yaar!\n","How do you think I feel when you say that?\n")
    return random.choice(responses)

AlienBot = RuleBot()
AlienBot.greet()